name: Build

on:
  push:

env:
  RUST_LOG: debug
  CARGO_INCREMENTAL: 0

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install wasm target
        shell: bash
        run: |
          rustup target add wasm32-wasi

      - name: Build plugin
        shell: bash
        run: |
          cargo build-wasi --release
          cp target/wasm32-wasi/release/swc_plugin_import_jsx_pragma.wasm .

      - uses: actions/upload-artifact@v3
        with:
          name: wasm-wasi
          path: swc_plugin_import_jsx_pragma.wasm
  test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: wasm-wasi

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          run_install: true

      - name: Run integration tests
        shell: bash
        run: |
          pnpm test
